apiVersion: app.terraform.io/v1alpha2
kind: Workspace
metadata:
  name: vlan3710
spec:
  organization: camrossi
  project:
    name: fab2
  token:
    secretKeyRef:
      name: tfc-owner
      key: token
  name: vlan3710
  description: Kubernetes Operator Automated Workspace
  applyMethod: auto
  terraformVersion: 1.9.5
  terraformVariables:
    - name: tenant
      value: "tf-vms-1"
    - name: app
      value: "vms"
    - name: vlan
      value: "3710"
    - name: phys_domain
      value: "uni/phys-ocp_sr_iov-secondary"
    - name: ports
      hcl: true
      value: >
        ["topology/pod-1/protpaths-201-202/pathep-[ocpbm-bm-03-bond1]",
        "topology/pod-1/protpaths-201-202/pathep-[bm-02-bond1]"]
    - name: apic
      sensitive: true
      value: "https://192.168.68.34"
    - name: apic_user
      value: "terraform"
    - name: apic_pass
      sensitive: true
      valueFrom:
        secretKeyRef:
          name: apicpass
          key: apic_pass
  environmentVariables:
      # Destroy and Apply without asking for permission
    - name: CONFIRM_DESTROY
      sensitive: false
      value: "0"
  executionMode: agent
  agentPool:
    name: agent-pool-ocp-baremetal