apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: vlan3711
  annotations:
    k8s.v1.cni.cncf.io/resourceName: bridge.network.kubevirt.io/br0
spec:
  config: >-
    {
    "cniVersion": "0.3.1",
    "name": "vlan3711",
    "plugins": [
        {
            "type": "cnv-bridge",
            "bridge": "br0",
            "vlan": 3711
        }
    ]
    }