apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vms-1
spec:
  destination:
    name: ''
    namespace: 'vms-1'
    server: 'https://api.ocp-sr-iov.cam.ciscolabs.com:6443'
  source:
    path: ansible-workflow/k8s/vms-provisioning
    repoURL: 'https://github.com/camrossi/gitops-vms.git'
    targetRevision: HEAD
    directory:
      jsonnet:
        extVars:
          - name: namespace
            value: $ARGOCD_APP_NAMESPACE
          - name: bridge
            value: br0

  sources: []
  project: default
  targetRevision: HEAD