tenant_name: gitops-ansible-vms-1
vrf_name: vrf

bridge_domains:
  - name: 10.1.200.0_24
    mode: L3
    gateway: 10.1.200.1/24
    scope: [private]

  - name: 10.1.201.0_24
    mode: L3
    gateway: 10.1.201.1/24
    scope: [private]

  - name: 10.1.202.0_24
    mode: L3
    gateway: 10.1.202.1/24
    scope: [private]

  - name: 10.1.203.0_24
    mode: L3
    gateway: 10.1.203.1/24
    scope: [private]

  - name: 10.1.204.0_24
    mode: L3
    gateway: 10.1.204.1/24
    scope: [private]

  - name: 10.1.205.0_24
    mode: L3
    gateway: 10.1.205.1/24
    scope: [private]

application_profiles:
  - name: vms-1
  - name: vms-2

endpoint_groups:
  - name: vlan-3710
    ap: vms-1
    bd: 10.1.200.0_24
    domains:
      - type: phys
        domain: ocp_sr_iov-secondary

  - name: vlan-3711
    ap: vms-1
    bd: 10.1.201.0_24
    domains:
      - type: phys
        domain: ocp_sr_iov-secondary

  - name: vlan-3712
    ap: vms-1
    bd: 10.1.202.0_24
    domains:
      - type: phys
        domain: ocp_sr_iov-secondary

  - name: vlan-3713
    ap: vms-2
    bd: 10.1.203.0_24
    domains:
      - type: phys
        domain: ocp_sr_iov-secondary

  - name: vlan-3714
    ap: vms-2
    bd: 10.1.204.0_24
    domains:
      - type: phys
        domain: ocp_sr_iov-secondary

  - name: vlan-3715
    ap: vms-2
    bd: 10.1.205.0_24
    domains:
      - type: phys
        domain: ocp_sr_iov-secondary
#filters:
#  - name: https
#    ether_type: ip
#    ip_protocol: tcp
#    dst_port_start: 443
#    dst_port_end: 443
#  - name: dns
#    ether_type: ip
#    ip_protocol: udp
#    dst_port_start: 53
#    dst_port_end: 53
#  - name: icmp
#    ether_type: ip
#    ip_protocol: icmp
#  - name: mariadb
#    ether_type: ip
#    ip_protocol: tcp
#    dst_port_start: 3306
#    dst_port_end: 3306
#
#contracts:
#  - name: web_to_app_con
#    descr: Communication between web servers and application backend
#    scope: application-profile
#    subject: https_icmp
#    reverse_filter: yes
#    filters:
#      - https
#      - icmp
#  - name: app_to_db_con
#    descr: Communication between application backend and databases
#    scope: application-profile
#    subject: mariadb_icmp
#    reverse_filter: yes
#    filters:
#      - mariadb
#      - icmp
#  - name: any_to_log_con
#    descr: Communication between any component and log
#    scope: application-profile
#    subject: https
#    reverse_filter: yes
#    filters:
#      - https
#  - name: any_to_dns_con
#    descr: Communication between any component and dns
#    scope: application-profile
#    subject: dns_icmp
#    reverse_filter: yes
#    filters:
#      - dns
#      - icmp
#  - name: app_to_auth_con
#    descr: Communication between application backend and authentication services
#    scope: application-profile
#    subject: https_icmp
#    reverse_filter: yes
#    filters:
#      - https
#      - icmp
#  - name: cache_to_db_con
#    descr: Communication between application backend and database cache
#    scope: application-profile
#    subject: mariadb_icmp
#    reverse_filter: yes
#    filters:
#      - mariadb
#      - icmp
#

