physical_domains:
  - name: rpis-c1
    type: phys
    vlan_pool: rpis-vms
    allocation: static


aaeps:
  - name: rpis
    aep_to_domain:
      - domain: rpis-c1
        type: phys
      - domain: phys
        type: phys
      - domain: ocp_sr_iov-secondary
        type: phys
      - domain: ocp_sr_iov-secondary
        type: l3dom
    aci_aep_to_epg:
      - tenant_name: rpi_vms
        app_name: vms-1
        epg_name: vlan-3801
        vlan: 3801
      - tenant_name: rpi_vms
        app_name: vms-1
        epg_name: vlan-3802
        vlan: 3802

vlan_pools:
- name: rpis-vms
  allocation: static
  ranges:
    - from: 3800
      to: 3899
      allocation: static

