tenant_name: rpi_vms
vrf_name: vrf

bridge_domains:
  - name: 192.168.21.0_24_bd
    mode: L3
    gateway: 192.168.21.1/24
    scope: [private]
  - name: 192.168.22.0_24_bd
    mode: L3
    gateway: 192.168.22.1/24
    scope: [private]


app_name: vms-1
epgs:
  - name: vlan-3801
    bd: 192.168.21.0_24_bd
    prefGroup: no
    #contracts:
    #  - contract: external_to_web_con
    #    type: consumer
    #  - contract: web_to_app_con
    #    type: consumer
    #  - contract: any_to_log_con
    #    type: consumer
    domains:
      - type: phys
        domain: phys

  - name: vlan-3802
    bd: 192.168.22.0_24_bd
    prefGroup: no
    #contracts:
    #  - contract: app_to_db_con
    #    type: consumer
    #  - contract: web_to_app_con
    #    type: provider
    #  - contract: app_to_auth_con
    #    type: consumer
    #  - contract: any_to_log_con
    #    type: consumer
    domains:
      - type: phys
        domain: phys
    #ports:
    #  - interface: vpc_iac
    #    type: vpc
    #    mode: regular
    #    pod: 1
    #    leafs: 101-102
    #    encap: 302


#filters:
#  - name: https
#    ether_type: ip
#    ip_protocol: tcp
#    dst_port_start: 443
#    dst_port_end: 443
#  - name: dns
#    ether_type: ip
#    ip_protocol: udp
#    dst_port_start: 53
#    dst_port_end: 53
#  - name: icmp
#    ether_type: ip
#    ip_protocol: icmp
#  - name: mariadb
#    ether_type: ip
#    ip_protocol: tcp
#    dst_port_start: 3306
#    dst_port_end: 3306
#
#contracts:
#  - name: web_to_app_con
#    descr: Communication between web servers and application backend
#    scope: application-profile
#    subject: https_icmp
#    reverse_filter: yes
#    filters:
#      - https
#      - icmp
#  - name: app_to_db_con
#    descr: Communication between application backend and databases
#    scope: application-profile
#    subject: mariadb_icmp
#    reverse_filter: yes
#    filters:
#      - mariadb
#      - icmp
#  - name: any_to_log_con
#    descr: Communication between any component and log
#    scope: application-profile
#    subject: https
#    reverse_filter: yes
#    filters:
#      - https
#  - name: any_to_dns_con
#    descr: Communication between any component and dns
#    scope: application-profile
#    subject: dns_icmp
#    reverse_filter: yes
#    filters:
#      - dns
#      - icmp
#  - name: app_to_auth_con
#    descr: Communication between application backend and authentication services
#    scope: application-profile
#    subject: https_icmp
#    reverse_filter: yes
#    filters:
#      - https
#      - icmp
#  - name: cache_to_db_con
#    descr: Communication between application backend and database cache
#    scope: application-profile
#    subject: mariadb_icmp
#    reverse_filter: yes
#    filters:
#      - mariadb
#      - icmp
#

aaeps:
  - name: rpis
    aep_to_domain:
      - domain: phys
        type: phys
      - domain: ocp_sr_iov-secondary
        type: phys
      - domain: ocp_sr_iov-secondary
        type: l3dom
    aci_aep_to_epg:
      - tenant: rpi_vms
        ap: vms-1
        epg: vlan-3801
        encap: vlan-3801
      - tenant: rpi_vms
        ap: vms-1
        epg: vlan-3802
        encap: vlan-3802