apiVersion: app.terraform.io/v1alpha2
kind: Workspace
metadata:
  name: vsc
  annotations:
    workspace.app.terraform.io/run-type: "apply"
spec:
  organization: camrossi
  project:
    name: fab2
  token:
    secretKeyRef:
      name: tfc-owner
      key: token
  name: vsc
  description: Kubernetes Operator Automated Workspace
  applyMethod: auto
  terraformVersion: 1.9.5
  versionControl:
    repository: camrossi/gitops-vms
    branch: main
    oAuthTokenID: "xxxxxxxx"
  workingDirectory: workflow/nac
  terraformVariables:
    - name: apic_url
      sensitive: true
      value: "https://192.168.68.34"
    - name: apic_user
      value: "terraform"
    - name: apic_pass
      sensitive: true
      valueFrom:
        secretKeyRef:
          name: apicpass
          key: apic_pass
  executionMode: agent
  agentPool:
    name: agent-pool-ocp-baremetal
