apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: ovs-br1-multiple-networks 
spec:
  nodeSelector:
    kubevirt-cluster: c1
  desiredState:
    interfaces:
    - name: ovs-br1 
      description: |-
        A dedicated OVS bridge with eth1 as a port
        allowing all VLANs and untagged traffic
      type: ovs-bridge
      state: up
      bridge:
        allow-extra-patch-ports: true
        options:
          stp: false
        port:
        - name: bond1
    ovn:
      bridge-mappings:
      - localnet: vlan3737
        bridge: ovs-br1 
        state: present 
      - localnet: vlan3738
        bridge: ovs-br1 
        state: present 