apiVersion: v1
items:
  - apiVersion: k8s.cni.cncf.io/v1
    kind: NetworkAttachmentDefinition
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/resourceName: bridge.network.kubevirt.io/br0
      name: vlan3711
    spec:
      config: |-
        {
            "cniVersion": "0.3.1",
            "name": "vlan3711",
            "plugins": [
                {
                    "bridge": "br0",
                    "type": "cnv-bridge",
                    "vlan": 3711
                }
            ]
        }
  - apiVersion: app.terraform.io/v1alpha2
    kind: Module
    metadata:
      name: aci-module-vlan3711
    spec:
      destroyOnDeletion: true
      module:
        source: github.com/camrossi/gitops-vms/terraform/vms-automation
      organization: camrossi
      token:
        secretKeyRef:
          key: token
          name: tfc-owner
      variables:
        - name: tenant
        - name: app
        - name: vlan
        - name: phys_domain
        - name: ports
        - name: apic_url
        - name: apic_user
        - name: apic_pass
      workspace:
        name: vlan3711
  - apiVersion: app.terraform.io/v1alpha2
    kind: Workspace
    metadata:
      name: vlan3711
    spec:
      agentPool:
        name: agent-pool-ocp-baremetal
      applyMethod: auto
      description: Kubernetes Operator Automated Workspace
      executionMode: agent
      name: vlan3711
      organization: camrossi
      project:
        name: fab2
      terraformVariables:
        - name: tenant
          value: tf-vms-1
        - name: app
          value: vms
        - name: vlan
          value: "3711"
        - name: phys_domain
          value: uni/phys-ocp_sr_iov-secondary
        - hcl: true
          name: ports
          value: '["topology/pod-1/protpaths-201-202/pathep-[ocpbm-bm-03-bond1]"]'
        - name: apic_url
          sensitive: true
          value: https://192.168.68.34
        - name: apic_user
          value: terraform
        - name: apic_pass
          sensitive: true
          valueFrom:
            secretKeyRef:
              key: apic_pass
              name: apicpass
      terraformVersion: 1.9.5
      token:
        secretKeyRef:
          key: token
          name: tfc-owner
kind: List
