apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: vlan3737
spec:
  config: |
    {
            "cniVersion": "0.3.1", 
            "name": "vlan3737", 
            "type": "ovn-k8s-cni-overlay", 
            "topology": "localnet",
            "netAttachDefName": "vms-vlan3737/vlan3737"
    }